name: rrr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.2+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  just_audio: ^0.10.4
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.2.0
  animated_text_kit: ^4.2.3
  smooth_page_indicator: ^1.2.1
  flutter_gradient_button: ^0.0.1
  flutter_spinkit: ^5.2.2
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path_ios: "assets/icons/app_icon.png"
  image_path_android: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/sounds/dog_lang/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/character/
    - assets/icons/svgs/bottom_navigation_bar/
    - assets/icons/svgs/home_screen/
    - assets/datas/fortune/
    - assets/datas/health/daily_checklist/
